#!/bin/bash

echo "--- Build application...\n";
npm run build;
echo "--- Build application API docs...\n";
npm run doc;
echo "--- Commit "$1"...\n";
git add . && git commit -am "$1";
echo "--- Github deploy...\n";
git push origin master;
